# Generated by Django 5.1.3 on 2024-11-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
