# Generated by Django 5.1.3 on 2024-11-19 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
